# config.yaml
download:
  base_dir: "data"               # 下载根目录
  biz: ["spot"]     # 支持多个 biz
  market: ["BTC_USDT"] # 支持多个 market
  types:
    - "candlesticks_30s"
    - "candlesticks_1m"
    - "candlesticks_5m"
    - "candlesticks_1h"
  start_date: "2023-01-01 00:00"  # 开始时间（本地时间，脚本自动转为UTC）
  end_date: "2026-02-01 00:00"    # 结束时间（本地时间）

logging:
  log_dir: "./spot_logs"

history_file: "./spot_history.log"
